# Welcome to Numpy Tutorial 

In [1]:
import numpy as np

In [2]:
myarr=np.array([[2,4,5,7,8]],np.int64)

In [3]:
 myarr

array([[2, 4, 5, 7, 8]], dtype=int64)

In [4]:
myarr[0,1]

4

In [5]:
myarr[0]

array([2, 4, 5, 7, 8], dtype=int64)

In [6]:
myarr.shape

(1, 5)

In [7]:
myarr.dtype

dtype('int64')

In [8]:
myarr[0,1]=37

In [9]:
myarr

array([[ 2, 37,  5,  7,  8]], dtype=int64)

# Array Creation : Conversion from other python structures 

In [10]:
listarray=np.array([[1,2,3],[5,6,7],[4,8,9]])

In [11]:
listarray

array([[1, 2, 3],
       [5, 6, 7],
       [4, 8, 9]])

In [12]:
listarray.dtype

dtype('int32')

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size


9

In [15]:
np.array({34,55,67})

array({34, 67, 55}, dtype=object)

In [16]:
zeros=np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
range=np.arange(15)

In [19]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
lspace=np.linspace(1,5,12)

In [21]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [22]:
emp=np.empty((4,6))

In [23]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.20161526e-306, 1.89146896e-307, 7.56571288e-307],
       [4.00544531e-307, 1.11261095e-306, 3.56043054e-307,
        1.37961641e-306, 2.22518251e-306, 1.33511969e-306],
       [1.69118108e-306, 8.06632139e-308, 1.20160711e-306,
        1.69119330e-306, 1.29062229e-306, 1.42417222e-306],
       [1.33512648e-306, 7.56596412e-307, 9.34601642e-307,
        1.78020169e-306, 8.34445562e-308, 3.91792476e-317]])

In [24]:
emp_like=np.empty_like(lspace)

In [25]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [26]:
ide=np.identity(45)

In [27]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [28]:
ide.shape

(45, 45)

In [29]:
arr=np.arange(99)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [34]:
arr=arr.reshape(3,33)

In [35]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [36]:
arr=arr.ravel()

In [37]:
arr.shape

(99,)

In [38]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [39]:
ar = np.array(x)

In [40]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
ar.sum(axis=0)

array([12, 15, 18])

In [42]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [43]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [44]:
ar.flat

In [45]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [46]:
ar.ndim

2

In [47]:
ar.size

9

In [48]:
ar.nbytes

36

In [51]:
one=np.array([1,222,0,4,5])

In [52]:
one.argmax()

1

In [53]:
one.argmin()

2

In [54]:
one.argsort()

array([2, 0, 3, 4, 1], dtype=int64)

In [55]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
ar.argmin()

0

In [57]:
ar.argmax()

8

In [58]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [59]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [60]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [62]:
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
ar2 = np.array([[11, 22, 31],
       [45, 54, 65],
       [137, 38, 49]])

In [65]:
ar + ar2

array([[ 12,  24,  34],
       [ 49,  59,  71],
       [144,  46,  58]])

In [66]:
[324,34]+[22,44]

[324, 34, 22, 44]

In [67]:
ar*ar2

array([[ 11,  44,  93],
       [180, 270, 390],
       [959, 304, 441]])

In [68]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [69]:
ar.sum()

45

In [70]:
ar.max()

9

In [71]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [72]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
np.count_nonzero(ar)

9

In [74]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [75]:
ar[1,2]=0

In [77]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))

In [78]:
import sys

In [80]:
py_ar = [0,1,2,66,44]

In [81]:
np_ar=np.array(py_ar)

In [82]:
sys.getsizeof(1)*len(py_ar)

140

In [83]:
np_ar.itemsize*np_ar.size

20

In [84]:
np_ar.tolist()

[0, 1, 2, 66, 44]